### ISSUE TITLE
[codegen] shallow/deep copy support for Java

### ISSUE THREAD

**Issue by izgzhen** [CozySynthesizer/cozy#74]
TODO: state when & where it is needed and its importance

**Comment by Calvin-L** [comment]
Could you clarify what the scope of this issue is?

Some things you might mean, but I am not sure:
 - Cozy-synthesized classes should be copy-able
 - The inner classes that Cozy defines should be copy-able
 - There should be facilities inside Cozy's own codegen infrastructure for making deep or shallow copies

**Comment by izgzhen** [comment]
I think I mean "There should be facilities inside Cozy's own codegen infrastructure for making deep or shallow copies".

**Comment by izgzhen** [comment]
needs more motivation. WONTFIX.
